### ISSUE TITLE
Component: Social Share

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/health-commission#15]
Display the social media share icons for a post

- [x] Facebook
- [x] Twitter
- [x] Email
- [x] Print

**Comment by aleesteele** [comment]
A q as I start to build this: to keep this more modular, it makes sense to have a `post-header` include that has download pdf/cite this page/share social and a `post-header` that has tags/share social. Let me know if you would prefer another method.

**Comment by jnschrag** [comment]
@aleesteele You're not thinking modular enough. These are all separate components (hence why I made them separate issues/items to complete) and are independent from where they are in the layout. Some of them are located in the `page-highlights` component, which is included via the `page-header` component. Others will be located in a `page-footer` component that has yet to be created. Others are used in both places.

This issue only involves creating the social share component and it should be built in such a way that we can easily embed it wherever we need it on the site. The only thing this component should do is display the social media icons that allow the user to share, email, print, etc. the page when it is clicked on. Anything else is beyond the scope of this issue.

**Comment by aleesteele** [comment]
I get that they're all separate components, but hadn't seen that the `single post` issue was actually 3 components in one issue. Had only seen the placeholders in the `post` file itself and thought they were in the same post and was wondering about exactly that. Now I understand how these are being divided, thanks Jacque!
