### ISSUE TITLE
Placement of nav arrows on smaller screen

### ISSUE THREAD

**Issue by tuckabelle** [CSIS-iLab/health-commission#177]
On smaller screens, the nav arrows appear under the words
![71065E32-2770-4DB8-ADF3-A47FFFE5CFFB](https://user-images.githubusercontent.com/13002217/62778396-4bb04680-ba7e-11e9-978c-1221f309eb39.jpeg)

**Comment by jdromero88** [comment]
Hey @tuckabelle how can I recreate this? I cloned the repo and I don't see the arrows under the words on smalls screens.
Thanks!
