### ISSUE TITLE
Add Authors

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/health-commission#43]
Create the "Authors" content in `_authors`.

- [x] Add authors to `frasco.config.js` under `jekyll`
- [x] Add to `config.yml`

Front matter:
- [x] Title --> Label in Forestry should be "Name"
- [x] Job Title --> Label in Forestry should be "Title"
- [x] Description (short bio)

**Comment by jnschrag** [comment]
@leezaweb and @aleesteele I'm not sure which of you worked on this, but the authors collection was not set up correctly. Authors are not the same as commission members, although there is a lot of overlap.

Authors only need to have their `title`, `job_title`, `image`, and the post content (right panel) filled out. If we have a bio for them (we do for all the authors that also commissioners), that should be posted in the post content section, not a front matter field.

When you're fixing these, please check the name of the markdown file. It should only have the person's name, not their title. Example: `u-s-congressman-ami-bera.md` should be `ami-bera.md`. You can correct this either via your editor or in Forestry by clicking on the three buttons in the top right corner when editing the post.

**Comment by leezaweb** [comment]
#43 @jnschrag,

Authors are in. 

Is job_title, short_bio? Should the field key name change on the template?

Non-CSIS authors have placeholder images as bio photos. I expect photos for CSIS authors tomorrow and will put them into Google Drive for Anne, who has the template for prepping those assets.
