### ISSUE TITLE
Component: Content Type

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/health-commission#7]
Display the content type of the post.

This should link to the search page with the content type already filtered. My recommendation would be to put the URL in `config.yml` and then use it in the component. If you look at the tags component, you can see an example of that in action. Note that the value passed to the URL must be the plural form of the content type, not the singular one.

Link: `/search/?dFR[content_type][0]=Commentaries`
Link in `config.yml`: `/search/?dFR[content_type][0]=`

**Comment by aleesteele** [comment]
Notes on this as it's being worked on:
- When searching for 'content_type', the search function defaults to the `title_single`. Is there a way to easily search for `title_plural`? I
- Changing the styles based on whether it's a `featured post`, `secondary post`, or `individual page`.
- Combining `series` & `content_type`, and putting in `post-meta`.

**Comment by aleesteele** [comment]
Notes on this as this is being worked on:
- When searching for ‘content_type’, the search function defaults to the `title_single`, changing it `title_plural`.
- Changing the styles based on whether it’s a `featured post`, `secondary post`, or `individual page`.
- Combining `series` & `content_type`, and putting in `post-meta`.

**Comment by jnschrag** [comment]
> * When searching for ‘content_type’, the search function defaults to the `title_single`, changing it `title_plural`.

Can you clarify what you mean by this?
