### ISSUE TITLE
Misc Tweaks & Bugs

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/health-commission#89]
- [x] Themes "More Related Posts" link needs to be adjusted to be link to the proper search page **(L)**
- [x] Update footer description text **(L)**
  > The CSIS Commission on Strengthening America’s Health Security aims to chart a bold vision for the future of U.S. leadership in global health security, at home and abroad. The Commission brings together a distinguished and diverse group of senior leaders who bridge the health and security fields, comprising members of Congress, past administrations, industry, foundations, universities, and NGOs, and the Commission is advised by a group of preeminent subject experts. This is a two-year effort organized by the CSIS Global Health Policy Center.
- [x] Tag block formatting **(J)**
- [x] Footnotes formatting on posts **(L)**
- [x] Images to home page **(J)**
  - Note that images should extend to edges until 1440px and then have padding on the outer edge.
- [x] Top of home page should have gradient **(J)**
- [x] Check with Tucker on split column list on header dropdown **(J)**
- [x] Check width of border lines between references and authors block on single post page; it's causing a horizontal scroll bar **(J)**
- [x] Make entire featured home page block a link **(J)**
  - *Note*: Can't do this because it would invalidate the links to the post meta within the post
- [x] "Navigate by Name" text on About page should also trigger the menu to open, not just clicking on the icon **(L)**
- [x] Look at copyright margin on left side. It should be flush to the left hand side like the rest of the footer content is. **(L)**
- [x] Theme "in depth" posts should have "Commentary" content type **(A)**
- [x] Author Image and short bio on author archive **(A)**
- [x] Remove unnecessary Authors (anybody who hasn't actually authored a post) **(L)**
- [x] Pagination no results styles **(J)**
- [x] Remove the featured event from home page
- [x] Capitalize the end of the theme names only, not the start/ending
- [x] Add photo caption to page highlights **(A)**
- [x] Add the iLab about credit (grab from bottom of ChinaPower)
- [x] Check event link in header/make block element **(J)**
- [x] Event posts featured image should fall back to event archive image if one is not specified **(L)**
- [x] Podcast elements should be centered in the post content
- [x] Reduce height on full bio modal on members page
- [x] Photos on cloudinary version number nonsense **(J)**
- [x] Video/podcast credit should be in italics
- [x] John Hillman need's a short title
- [x] Cite this page borked
- [x] Empty "references" content in forestry
- [x] "Committee Launch" event isn't showing up under /events
- [x] Add Google Analytics **(J)**
- [x] Correct homepage secondary featured posts
- [x] Photo captions for the About page: **(A)**
- [x] Photo for August 6 “Health Security in a Disordered World” Event page 
- [x] Add featured posts for each theme page: 
- [x] Correct excerpt for “Navigating the Ebola Outbreak in the Democratic Republic of the Congo” 
- [x] Unpublish series that don't have any posts associated with them yet **(A)**
- [x] A pseudo element on page-highlights is blocking clicks on components like share and cite on Mobile
- [x] Fix logic for post meta authors: Pass the array of authors to the post-meta-authors include as a parameter. If it is set, use that as the authors array. If it isn't, default to the post authors. This parameter should be used in the page-header only. **(L)**
- [x] Related posts should exclude the "next" post **(L)**
- [x] Hide author block if there are no authors **(J)**

## Later/Post-Launch
- [x] Documents List on event posts **(L)**

**Comment by aleesteele** [comment]
Other Notes*
- [ ] Fix PDF, Cite this Page and Share to have the same margins + 'Cite this Page' should show 'Cite' on mobile
- [ ] Add twitter link to page footer (CSISHealth)

**Comment by jnschrag** [comment]
> * [ ]  Photo on about and members page differs in height from events (difference in type: archive vs post)

This is intentional.
