### ISSUE TITLE
Component: List of author names

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/health-commission#9]
Display a list of author names

- [x] Names should link to the author's page
- [x] List should be comma separate if more than 3 authors (eg. Jane Dot, John Doe, and Harry Potter)
- [x] Ultimate & penultimate names should be separate by "and" (eg. Jane Dot and John Doe)

**Comment by aleesteele** [comment]
Notes as these are being worked on –
- `array to sentence` unfortunately doesn't work as . currently working out how to do this manually, inserting the 'and' before the final part of the array
-  changing styles whether it was in `featured`, `secondary` or `page`

**Comment by jnschrag** [comment]
> * `array to sentence` unfortunately doesn't work as . currently working out how to do this manually, inserting the 'and' before the final part of the array

You can use the `forloop.last` to adjust what is rendered for just the last value in the array. See here: https://stackoverflow.com/a/34568968
